<<<<<<< HEAD
[project]
name = "performance_analyst"
version = "0.1.0"
description = "performance_analyst using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.7.2"
]

[project.scripts]
performance_analyst = "performance_analyst.main:run"
run_crew = "performance_analyst.main:run"
train = "performance_analyst.main:train"
replay = "performance_analyst.main:replay"
test = "performance_analyst.main:test"
run_with_trigger = "performance_analyst.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
=======
[project]
name = "performance_analyst"
version = "0.1.0"
description = "performance_analyst using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.7.2"
]

[project.scripts]
performance_analyst = "performance_analyst.main:run"
run_crew = "performance_analyst.main:run"
train = "performance_analyst.main:train"
replay = "performance_analyst.main:replay"
test = "performance_analyst.main:test"
run_with_trigger = "performance_analyst.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
>>>>>>> 43be04e7cc493dc7a65f76c0c5b598772f91571e
